### ISSUE TITLE
Reverse of margin and padding: x x x x;

### ISSUE THREAD

**Issue by Rakonda** [less/less-plugin-rtl#2]
Hello,
i'm using this awesome plugin and its helps me a lot, but the reserve to rtl in margin and padding:x x x x; not working, here is example when i use padding: 17px 0 17px 60px; the rtl version came out the same padding: 17px 0 17px 60px; not padding: 17px 60px 17px 0; and the same thing with margin.

**Comment by lukeapage** [comment]
Hi thanks,

would you be able to contribute a test case that fails? Preferably to this repo..

We do specifically test for this case...

https://github.com/less/less-plugin-rtl/blob/master/test/css/rtl/test.css#L17
https://github.com/less/less-plugin-rtl/blob/master/test/less/rtl/test.less#L23

so maybe something is a bit different .. ?

**Comment by Rakonda** [comment]
oh thanks, it works now.
